version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  app:
    build: .
    depends_on:
      - db

volumes:
  db-data: {}
