name: webpack

on: [push]

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build:prod
        env:
          CI: true
          NODEMON: false
